#!/usr/bin/bash 

clear
read -p "Digite seu nome: " NAME
echo $NAME | grep  -E '^[A-Za-z]{1}';
    if [[  $? -eq 0  ]]; then
        echo "Login Correto"
        else
        echo "Login Incorreto"
    fi
read -p "Email: " MAIL
echo  MAIL | grep  '^([A-Za-z0-9])@[a-z]\.[a-z]{2,3}';
    if [[ $? -eq 0  ]]; then 
        echo "Email Correto"
        else
        echo "Email Incorreto"
    fi
 read -p "Telefone: " FONE
 echo FONE | grep -E '^[(][0-9]{2}[)][0-9]{5}+-[0-9]{4}';
       if [[ $? -eq 0  ]]; then 
        echo "Telefone Correto"
        else
        echo "Telefone Incorreto"
    fi
read -p "RG: " RG
echo RG | grep -E '^[0-9]{2}\.[0-9]{3}-[0-9]{1}';
   if [[ $? -eq 0  ]]; then 
        echo "RG Correto"
        else
        echo "RG Incorreto"
    fi
    read -p "CPF: " CPF
echo CPF | grep -E '^[0-9]{3}\.[0-9]{3}\.[0-9]{3}-[0-9]{3}';
   if [[ $? -eq 0  ]]; then 
        echo "CPF Correto"
        else
        echo "CPF Incorreto"
    fi
    read -p "IP: " IP
echo IP | grep -E '^[0-9]{2,3}\.[0-9]{2,3}\.[0-9]{2,3}\.[0-9]{2,3}';
   if [[ $? -eq 0  ]]; then 
        echo "IP Correto"
        else
        echo "IP Incorreto"
    fi
    read -p "Mascara:  " MASK
echo MASK | grep -E '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'; 
   if [[ $? -eq 0  ]]; then 
        echo "Mascara Correto"
        else
        echo "Mascara Incorreto"
    fi

